# Generated by Django 2.2.7 on 2019-12-11 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('product_count', models.IntegerField(default=0)),
                ('url', models.URLField()),
                ('off_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('nutriscore', models.CharField(max_length=1, verbose_name='Nutriscore')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='Marque')),
                ('itemcode', models.CharField(blank=True, max_length=150, verbose_name='Code Produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.URLField(blank=True, default='http://www.imagespourtoi.com/image/892.html')),
                ('openfoodfacts_link', models.URLField(blank=True, verbose_name='URL Openfoodfacts')),
                ('categories', models.ManyToManyField(to='pur_beurre.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sauvegardé par')),
                ('saved_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pur_beurre.Product', verbose_name='Produit sauvegardé')),
            ],
        ),
        migrations.AddConstraint(
            model_name='savedproduct',
            constraint=models.UniqueConstraint(fields=('saved_by', 'saved_product'), name='saved_association'),
        ),
    ]
